views:
  - name: abd_analytics

    cubes:
      - join_path: ext_invoices
        prefix: false
        includes:
          # IDs
          - invoice_id
          - owner_id
          
          # Timing
          - date_day

          # Properties
          - store_address
          - store_name
          - store_city
          - item_description
          - category_name
          - brand_name
          - vendor_name
          - owner_name

          # Measures | Absolute
          - invoice_count
          - bottles_sold
          - volume_sold_liters
          - retail_value_items_sold

          # Measures | Ratios
          - average_sale_dollars_per_invoice
          - average_bottles_sold_per_invoice
          - average_sale_dollars_per_bottle
          - average_liter_per_bottle
          - average_retail_value_per_liter

          # Measures | Trailing
          - invoice_count_12m
          - bottles_sold_12m
          - volume_sold_liters_12m
          - retail_value_items_sold_12m

          # Measures | Growth
          - retail_value_items_sold_annual_growth_ratio
